### ISSUE TITLE
iOS 17 beta issue: abnormal search results.

### ISSUE THREAD

**Issue by flipped0119** [mazzzystar/Queryable#3] opened 2023-07-11 08:33 UTC
In iOS 17 beta 3, regardless of the keyword used, the search results are always the same.

**Comment by mazzzystar** [comment] 2023-07-11 08:51
It should be a newly introduced bug in iOS 17 beta. The plan is to wait for the beta version to stabilize before investigating the issue. The official release is expected around September, so there is still some time to go :)

**Comment by RupGautam** [comment] 2023-07-12 14:32
I can confirm the results are the same, not always, but most of the time.

**Comment by mazzzystar** [comment] 2023-07-12 14:40
@RupGautam 
I've debugged the issue. I found that all text inputs were embedded into the same value in iOS 17 beta. However, it works correctly on iOS 16. I suspect it was the issue related with model loading, didn't figured out the problem yet.

**Comment by RupGautam** [comment] 2023-07-12 14:49
"Deep green/blue water with mountains around" 

"Deep green/blue water without mountains around" 

Gives me the same results. ⁉️

**Comment by mazzzystar** [comment] 2023-07-12 14:52
@RupGautam Right, you're using iOS 17 beta. As I've mentioned before, every input query in iOS 17 got the same text embedding vector output, which may be cause by model loading failure.

**Comment by mazzzystar** [comment] 2023-07-15 06:30
@RupGautam @flipped0119 
did you use Xcode 15 beta to compile?  I've just tried on my `Xcode 14.3.1` and it works correctly. I do got abnormal result on my Xcode 15, it seems to be a Xcode issue.

**Comment by Dealizey** [comment] 2023-07-19 06:58
@mazzzystar So has the bug been fixed with Xcode beta?

**Comment by mazzzystar** [comment] 2023-07-19 07:10
> @mazzzystar So has the bug been fixed with Xcode beta?

No, I'm saying that when using Xcode 14 + iOS 17 beta to run the app, everything seems to be normal. While in Xcode 15 + iOS 17 the issue occurs.

**Comment by mazzzystar** [comment] 2023-07-23 16:59
Confirmed, when upgraded to `iOS 17 public beta`, everything back to normal.

**Comment by mazzzystar** [comment] 2023-09-22 11:21
@flipped0119 @RupGautam @Dealizey 
Finally I found the issue.  For `iOS 17`, ou need to explicitly set d`type=np.int32` for the input tensor when export model.
```python
max_seq_length = 77

text_encoder_model = ct.convert(
            traced_model,
            convert_to="mlprogram",
            minimum_deployment_target=ct.target.iOS16,
            inputs=[ct.TensorType(name="prompt",
                                 shape=example_input.shape),
                                 dtype=np.int32)],
            outputs=[ct.TensorType(name="embOutput", dtype=np.float32)],
        )
```

**Closed** 2023-09-22 11:41 UTC
Labels: bug, enhancement

**Comment by Dealizey** [comment] 2023-09-22 12:08
@mazzzystar Great! When will this bug fix be published?

**Comment by mazzzystar** [comment] 2023-09-22 12:30
@Dealizey 
It's just published. https://apps.apple.com/us/app/queryable-find-photo-by-text/id1661598353

**Comment by Dealizey** [comment] 2023-09-22 12:39
It's quite interesting that the Chinese App Store didn't show that update, but the US one did. Maybe it's because of the CDN configuration.

**Comment by mazzzystar** [comment] 2023-09-22 12:42
@Dealizey  Queryable & 寻隐 are using two models, so it's two app. In Chinese version, this update is still under beta testing.

**Comment by Dealizey** [comment] 2023-09-22 12:44
Thanks! Hope the Chinese version will be published soon.❤️❤️❤️

**Comment by mazzzystar** [comment] 2023-09-23 05:17
@Dealizey It is available now.

**Comment by Dealizey** [comment] 2023-09-23 10:20
Got that. Thanks a lot!
